backend:
  name: test-repo
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "conteudo"
    label: "Home"
    files:
      - file: "conteudo.json"
        label: "Página Principal"
        name: "pagina"
        fields:
          - { label: "Título", name: "titulo", widget: "string" }
          - { label: "Descrição", name: "descricao", widget: "text" }
          - { label: "Imagem", name: "imagem", widget: "image" }